### ISSUE TITLE
The dropbox link might require permissions from you. (It doesn't open.)

### ISSUE THREAD

**Issue by arjunakula** [jiasenlu/vilbert_beta#10]
The dropbox link might require permissions from you. (It doesn't open.)

Also, we would like to train the model on RefCOCOg. Would it be possible to get some pointers on how to use your code to train the model on RefCOCOg (for example, how to map/format the MattNet features to your features features_h5path1 and features_h5path2).  This would be very helpful. (Did you also try RefCOCOg in addition to RefCOCO+). Thanks a lot!

_Originally posted by @arjunakula in https://github.com/jiasenlu/vilbert_beta/issues/9#issuecomment-527708237_

**Comment by jiasenlu** [comment]
hmm, I use a chrom incognito mode and the link seems work. Can you tell which link is invalid? 

To train RefCOCOg, I use the bounding box proposal from https://github.com/lichengunc/MAttNet
you can download the pre-computed proposal from here. http://bvision.cs.unc.edu/licheng/MattNet/detections.zip

Then, you need to extract the features, use this script 
https://github.com/jiasenlu/bottom-up-attention/blob/master/tools/generate_tsv_gt.py

After you get the tsv file, you need to convert the lmdb file, the convert script is also provided in the 

https://github.com/jiasenlu/vilbert_beta/blob/master/script/convert_lmdb_refcoco+.py

you can follow this script to convert refcocog.

**Comment by arjunakula** [comment]
Many thanks Jiasenlu for the prompt reply and the detailed instructions to get features for refcocog!

The link that i was referring to is the following: https://www.dropbox.com/home/vilbert_release/data/referExpression

I tried opening it again but it didn't work. (You shared this link to download the files data/referExpression/refcoco+_resnet101_faster_rcnn_genome.lmdb and data/referExpression/refcoco+_gt_resnet101_faster_rcnn_genome.lmdb).

Thanks a lot once again!

**Comment by jiasenlu** [comment]
hmm

https://www.dropbox.com/sh/4jqadcfkai68yoe/AADRIB01HqsJnO9TMml_PZDca/refcoco%2B_gt_resnet101_faster_rcnn_genome.lmdb?dl=0&subfolder_nav_tracking=1

https://www.dropbox.com/sh/4jqadcfkai68yoe/AABlFfCTHasuS9LTDQKmOEU1a/refcoco%2B_resnet101_faster_rcnn_genome.lmdb?dl=0&subfolder_nav_tracking=1

can work on my side. it's wired.

**Comment by jiasenlu** [comment]
try 

https://www.dropbox.com/sh/4jqadcfkai68yoe/AADHI6dKviFcraeCMdjiaDENa?dl=0

**Comment by arjunakula** [comment]
Perfect! I am able to download the files now. Thanks a ton!

**Comment by jiasenlu** [comment]
close

**Comment by alice-cool** [comment]
https://github.com/jiasenlu/vilbert_beta/issues/10#issuecomment-528175471
Do you run the vqa 2.0 dropbox  lmdb file . I want to download the vqa2.0 dataset lmdb. But the link is not stable, always end abruptly..... Could you share a new link just like google drive , I want to download the dataset to reproduce the result 67.9?
