### ISSUE TITLE
Error when extract feature from faster rcnn

### ISSUE THREAD

**Issue by neverland7D** [jiasenlu/vilbert_beta#11]
when I use generate_tsv to extract feature from pretrained caffe model, I got error 
"Check failed: error == cudaSuccess (8 vs. 0)  invalid device function" 
which happend in this layer: 
caffe::PoolingLayer<>::Forward_gpu().
I've checked my caffe version is able to run with gpu, I have no idea what's wrong with it.

**Comment by jiasenlu** [comment]
I think you didn't install caffe correctly. please follow the original bottom-up repo to install caffe first. The caffe requires python2 and opencv.

**Comment by neverland7D** [comment]
> I think you didn't install caffe correctly. please follow the original bottom-up repo to install caffe first. The caffe requires python2 and opencv.

Thanks a lot for your reply!!
