### ISSUE TITLE
No such file or directory: 'data/VCR/val.jsonl'

### ISSUE THREAD

**Issue by brian7685** [jiasenlu/vilbert_beta#14]
In the 'vlbert_tasks.yml', which files do train.jsonl and val.jsonl refers to?

train_annotations_jsonpath: data/VCR/train.jsonl
val_annotations_jsonpath: data/VCR/val.jsonl

Thanks!

**Comment by shravan1394** [comment]
Hey @brian7685 , Could you let me know on where to find the train.jsonl and val.jsonl for VCR?
Thanks
