### ISSUE TITLE
Train ViLBERT for DownStream Tasks for VCR

### ISSUE THREAD

**Issue by brian7685** [jiasenlu/vilbert_beta#17]
I encountered an issue in:
File "/home/XXX/vilbert_beta/vilbert/vilbert.py", line 322, in forward
position_ids = position_ids.unsqueeze(0).expand_as(input_ids)
RuntimeError: The expanded size of the tensor (60) must match the existing size (4) at non-singleton dimension 2.  Target sizes: [16, 4, 60].  Tensor sizes: [1, 4]

From the code we can see:
seq_length = input_ids.size(1)
position_ids = torch.arange(
      seq_length, dtype=torch.long, device=input_ids.device
)
The input_ids is [16, 4, 60]
position_ids is [4]
How do we fit the 60?
Thanks!

**Comment by rmrao** [comment]
I encountered this as well. It seems to be a bug in [line 89 of `vilbert/task_utils.py`](https://github.com/jiasenlu/vilbert_beta/blob/eee2a6944043ce787db8bdf3cdac892914a4b3e9/vilbert/task_utils.py#L89). The identifier 'TASK1' is omitted - I think it should be added there.

**Comment by yangzhch6** [comment]
@rmrao  Your answer has solved my problem! Thank you very much. What I want to add is, in line 29 of vilbert/task_utils.py, I think the identifier 'TASK1' is omitted.

**Comment by zc-alexfan** [comment]
Just an extra comment. We need to change this line as well in the [validation function](https://github.com/jiasenlu/vilbert_beta/blob/eee2a6944043ce787db8bdf3cdac892914a4b3e9/vilbert/task_utils.py#L29).
