### ISSUE TITLE
lmdb pre processing file for VQA

### ISSUE THREAD

**Issue by deepanks** [jiasenlu/vilbert_beta#3]
Could you please share the pre-processing file to convert to lmdb for vqa.

**Comment by jiasenlu** [comment]
done

**Comment by alice-cool** [comment]
https://github.com/jiasenlu/vilbert_beta/issues/3#issue-484791465

Could you share the the pre-processing file,? Is it from peterson bottom up and top down 10~100 tsv file?
And do you reproduce the same result of the paper. I only got the score 0.0
