### ISSUE TITLE
Error "FileNotFoundError: [Errno 2] No such file or directory: 'data/VQA/cache/trainval_ans2label.pkl'"

### ISSUE THREAD

**Issue by zhm1995** [jiasenlu/vilbert_beta#44]
I got this error when I ran pre-trained VQA task. Does anybody know how to solve this?

**Comment by tranvansanghust** [comment]
@zhm1995  Did you solve this issue??

**Comment by iMayK** [comment]
@tranvansanghust , @zhm1995  were you able to resolve the issue?

**Comment by about608504** [comment]
@zhm1995 Hello, I encountered the same problem, can you please tell me how to solve it
