### ISSUE TITLE
i can't download Conceptual Captions pretrained model

### ISSUE THREAD

**Issue by jaeyun95** [jiasenlu/vilbert_beta#47]
I think I downloaded it before, but I get a 404 Not Found error. How should I download it? Should I get a Pretrained model of Conceptual Captions from the Vilbert-Multi-Task github?

**Comment by jiasenlu** [comment]
no, the ViLBERT-Multi-Task is using different image features. I just upload the correct checkpoint . Could you try again?

**Comment by jaeyun95** [comment]
thank you~~~~:)
