### ISSUE TITLE
The required pre-trained vilbert checkpoint is not released

### ISSUE THREAD

**Issue by JizeCao** [jiasenlu/vilbert_beta#5]
I found that you have released the checkpoint bert_base_6_layer_6_connect/pytorch_model_9.bin, which should be the checkpoint of VilBert after pretraining. However, in the fine tuning phase, the pretrain parameter wants the save/bert_base_6_layer_6_connect_freeze_0/pytorch_model_8.bin checkpoint rather than model_9. Are these two checkpoints the same one?

**Comment by jiasenlu** [comment]
yes, these are the same one. You can change that. I'll also release more ablations today if you want to try.

**Comment by linbojin** [comment]
> yes, these are the same one. You can change that. I'll also release more ablations today if you want to try.

any updates?

**Comment by arjunakula** [comment]
@JizeCao : can u share the link for downloading the file bert_base_6_layer_6_connect/pytorch_model_9.bin ? thanks!

**Comment by arjunakula** [comment]
> @JizeCao : can u share the link for downloading the file bert_base_6_layer_6_connect/pytorch_model_9.bin ? thanks!

my bad... was looking in the incorrect directory. found the file in Conceptual captions google drive link.
