### ISSUE TITLE
The download link for VCR feature is incorrect.

### ISSUE THREAD

**Issue by AeroXi** [jiasenlu/vilbert_beta#6]
![image](https://user-images.githubusercontent.com/31943024/64037249-bccbb100-cb87-11e9-9167-9a5c050090d2.png)
The download link for VCR is actually coco feature
I think it's a mistake.

**Comment by JizeCao** [comment]
Any update? I think the download link for VCR feature is still incorrect...

**Comment by JizeCao** [comment]
@jiasenlu I think the VCR feature's link is still incorrect. Would you like to fix it? Thanks!

**Comment by jiasenlu** [comment]
Thanks for pointing that out. I just fixed the link. Can you try again?

**Comment by JizeCao** [comment]
Yeah, I used your processed data and achieve a worse performance on
validation dataset about Q —> A task, 72.217. This is really wired…

Best,
Jize Cao

On Tuesday, September 3, 2019, Jiasen Lu <notifications@github.com> wrote:
> Thanks for pointing that out. I just fixed the link. Can you try again?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/cDAPsCV_OVnpH6FKno4rowO02PVGrZeV_H_cnGjAHRaJQE5ppLr5s5-2RuYyjJeRjrAjaf5KE7yKJvznTs4QLkjCzAErXQES7ZhIa7DfsjAsZ_voxS9zL2fYDu82oz6wvZCTMuBRuF8v1mS8IBssflTO0hop5QfMHc_tXBoX5WcE8D3YE9WjV872UQUcqxLd_oU4WUc2x89GikxRuc_2ySHnTh13q30akSqLiuzO7Q=s0-d-e1-ft#https://github.com/notifications/beacon/AHTDS5KOG5TARAKLARTR743QH2LIBA5CNFSM4ISPFQW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5Y46VQ.gif>
