### ISSUE TITLE
Referring Expression Evaluation

### ISSUE THREAD

**Issue by arjunakula** [jiasenlu/vilbert_beta#9]
Trying to evaluate referring expressions shows the following error:
lmdb.Error: data/referExpression/refcoco+_resnet101_faster_rcnn_genome.lmdb: No such file or directory

Could you let me know how to get the file refcoco+_resnet101_faster_rcnn_genome.lmdb. thanks!

**Comment by arjunakula** [comment]
From Mattnet, I get the following two files:
1. res101_coco_minus_refer_notime_det_feats.h5
2. res101_coco_minus_refer_notime_ann_feats.h5

But not sure how to change them to the following:
features_h5path1: data/referExpression/refcoco+_resnet101_faster_rcnn_genome.lmdb
features_h5path2: data/referExpression/refcoco+_gt_resnet101_faster_rcnn_genome.lmdb

**Comment by jiasenlu** [comment]
you can download the feature directly from https://www.dropbox.com/home/vilbert_release/data/referExpression.

**Comment by arjunakula** [comment]
The above link might require permissions from you. (It doesn't open.)

Also, we would like to train the model on RefCOCOg. Would it be possible to get some pointers on how to use your code to train the model on RefCOCOg (for example, how to map the MattNet features to your features features_h5path1 and features_h5path2).  This would be very helpful. Thanks a lot!

**Comment by lizhen2017** [comment]
> you can download the feature directly from https://www.dropbox.com/home/vilbert_release/data/referExpression.

Sorry, this url is invalid, would you please share again?
